[package]
name = "externref_bench"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = { path = "../../../wasm-bindgen" }
js-sys = { path = "../../../wasm-bindgen/crates/js-sys" }

[lib]
crate-type = ["cdylib", "rlib"]

